Repository viur-framework/viur-base, pull requests merged in 2023-09, with the labels that each got.

#109 Adjust `user_password_recovery.email` template for newer core implementation
  deploy/emails/user_password_recovery.email
Labels: refactoring

#102 Add templates for second factor user authentication
  deploy/html/user_login_secondfactor.html
  deploy/html/user_second_factor_choice.html
  deploy/html/user_secondfactor_add.html
  deploy/html/user_secondfactor_add_success.html
Labels: enhancement

#110 Upgrade python to `3.11`, `viur-core` to `v3.5.1` and `viur-cli` to `v1.0.16`
  .editorconfig
  Pipfile
  Pipfile.lock
  deploy/main.py
  deploy/requirements.txt
  project.json
Labels: dependencies
