Repository viur-framework/viur-base, pull requests merged in 2025-01, with the labels that each got.

#134 refactor: More clean-up on viur-base
  .gitignore
  deploy/.gcloudignore
  deploy/html/empty_list.html
  deploy/main.py
  deploy/modules/empty.py
  deploy/modules/file.py
  deploy/skeletons/empty.py
  deploy/skeletons/example.py
  deploy/vi_plugins/__init__.py
  deploy/vi_plugins/files.json
  project.json
  resources/allbones/README.md
  resources/allbones/modules/allbones.py
  resources/allbones/skeletons/allbones.py
  viur-project.md
Labels: refactoring, Priority: Medium

#138 feat: Update to viur-core~=3.7 and admin 4.7.4
  Pipfile
  Pipfile.lock
  deploy/requirements.txt
  project.json
Labels: dependencies, Priority: Medium

#139 feat: Extend `viur-gcloud-setup.sh` with command to create public bucket with ACL
  viur-gcloud-setup.sh
Labels: feature, Priority: Medium
